### ISSUE TITLE
Camera Thumbnail No Streaming

### ISSUE THREAD

**Issue by rcohnhead** [nzapponi/homebridge-simplisafe3#141] opened 2020-07-21 16:24 UTC
I have installed the plugin and everything is working perfectly. I'm running Homebridge off of my Mac mini. The cameras are showing up in the Home app, but they will not stream when I try to open them.

Here is what shows up in the logs:

(node:2086) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at spawn (child_process.js:542:16)
    at SS3SimpliCam.handleStreamRequest (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:473:46)
(node:2086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shamoon** [comment] 2020-07-21 16:39
Hi @rcohnhead, it looks like the ffmpeg binary didn’t install correctly. What method did you use to install the plugin? If you install as directed here or using Config UI X it should automatically pull the binaries, if not you may need to manually do so, see: https://github.com/homebridge/ffmpeg-for-homebridge

Of course if you’re comfortable you can build your own ffmpeg and point the plugin to that but you may need to adjust the parameters for encoding, etc

Keep us posted on your progress.

**Comment by shamoon** [comment] 2020-07-21 16:54
Ps. In particular the `--unsafe-perm` flag is important if youre installing the plugin manually via CLI and whether youre installing global (`-g`) or not can sometimes cause issues (Homebridge and all plugins can be installed globally or locally but global is usually easiest).

**Comment by rcohnhead** [comment] 2020-07-21 17:00
I tried uninstalling and reinstalling the SimpliSafe plugin through  Config UI X and am getting the same error. I can try to install ffmpeg-for -homebridge manually and see if it makes a difference.

**Comment by rcohnhead** [comment] 2020-07-21 17:13
I am still getting that error string in Homebridge.  One thing to note is that I can see the thumbnail updating in the Home App for the cameras, but when I click and try to stream the video, it stops responding. I am not sure how to install the plugin manually. I tried following the commands and inputting them into Terminal. Is that the correct way?

**Comment by shamoon** [comment] 2020-07-21 17:19
Try `sudo npm install -g --unsafe-perm ffmpeg-for-homebridge`, if that doesnt work you can also try `npm install -g --unsafe-perm homebridge-simplisafe3`.

Finally, if youre still having trouble you should enable the `debug` option for this plugin and debug for Homebridge (`-D`), restart and post your logs when you try to stream.

The fact that you still see thumbnails is normal (and a good indicator that the issue is just ffmpeg), thumbnail generation doesnt use ffmpeg.

**Comment by rcohnhead** [comment] 2020-07-21 17:31
Yes, I do think it is just ffmpeg because everything works flawlessly, but the streaming.

I tried the first command, just install ffmpeg for Homebridge and received this message: 

"> ffmpeg-for-homebridge@0.0.6 install /usr/local/lib/node_modules/ffmpeg-for-homebridge
> node install.js

ffmpeg-for-homebridge: darwin x64 is not supported, you will need to install/compile ffmpeg manually.
+ ffmpeg-for-homebridge@0.0.6
updated 1 package in 1.019s"

Streaming gave me the same error.

Then I tried running the SimpliSafe install command and received this message: 

"npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
+ homebridge-simplisafe3@1.6.7
updated 1 package in 2.647s"


I enabled debug and this was what came up when I tried streaming: 

(node:5255) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at spawn (child_process.js:542:16)
    at SS3SimpliCam.handleStreamRequest (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:473:46)
(node:5255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by rcohnhead** [comment] 2020-07-21 17:37
I wonder if it is because I am running a machine with High Sierra.

**Comment by shamoon** [comment] 2020-07-21 20:57
Ah yes, [ffmpeg-for-hombridge only supports macOS 10.14+](https://github.com/homebridge/ffmpeg-for-homebridge#supported-platforms). Your options would be to install or build and compile your own ffmpeg binary (honestly not as bad as it sounds) and then you may need to tweak the encoders used by this plugin in the settings. Lots of stuff online about this and if you have trouble the [homebridge discord server](https://discord.gg/kqNCe2D) is another good place to ask for help. Custom ffmpeg builds aren't really considered within the scope of this plugin itself, so I'm closing this but feel free to reach back out

**Closed by shamoon** 2020-07-21 20:57 UTC
Labels: question

**Comment by shamoon** [comment] 2020-07-22 07:14
(Not that it really helps you but after talking to the plugin dev, ffmpeg-for-homebridge will be updated to better explain the macOS requirements to the user).

**Comment by rcohnhead** [comment] 2020-07-22 07:45
You helped a lot. You helped me narrow it down to an issue with ffmpeg and not the plugin. What I finally ended up doing was using a Mojave patcher to install Mojave on my unsupported Mac Mini.  Then I was able to uninstall and reinstall your simplisafe plugin, which is now working perfectly, cameras and all.  Thank you.
