### ISSUE TITLE
SimpliCam: No Response

### ISSUE THREAD

**Issue by hubartt** [nzapponi/homebridge-simplisafe3#1] opened 2019-06-21 14:50 UTC
Awesome plugin!

I'm running Homebridge with HOOBS on a Raspberry Pi Zero W. 

My SimpliCam is showing up in the Home app but is returning "No Response".

Contact sensors are working great and so is the Arm/Disarm functionality. I'm not seeing my Glass Break sensor though.

**Comment by nzapponi** [comment] 2019-06-21 15:26
Thanks for the feedback!
Regarding the camera, it’s still highly experimental and I’m aware of a few issues with it. What I noticed is that my Simplicam connects when I’m on cellular but not when I’m on the same network as Homebridge. Not sure why yet. 

Regarding the glass break sensor, it’s not yet supported as I don’t have any to test with. Could you share your homebridge log?
There should be a line that says Sensor not yet supported and the sensor data right below. If you could share it, I’ll happily add support for the glass break sensor. 

Thanks

**Comment by hubartt** [comment] 2019-06-21 22:45
Hopefully this is helpful:

`[6/21/2019, 6:27:24 PM] [Security] Sensor not found, adding...
[6/21/2019, 6:27:24 PM] [Security] Camera not found, adding...
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Refreshing alarm state
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Refreshing sensor state
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Refreshing sensor state
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Refreshing sensor state
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Refreshing sensor state
[6/21/2019, 6:27:24 PM] [Security] Found device!
[6/21/2019, 6:27:24 PM] [Security] Found cached stream
[6/21/2019, 6:27:25 PM] [Security] Found cached stream
[6/21/2019, 6:27:25 PM] [Security] Refreshing accessories
[6/21/2019, 6:27:25 PM] [Security] Updated current state for SimpliSafe 3: OFF
[6/21/2019, 6:27:25 PM] [Security] Updated current state for Office Door: false, false
[6/21/2019, 6:27:25 PM] [Security] Updated current state for Side Door: false, false
[6/21/2019, 6:27:25 PM] [Security] Updated current state for Back Door: false, false
[6/21/2019, 6:27:25 PM] [Security] Updated current state for Front Door: false, false
[6/21/2019, 6:27:26 PM] [Security] Sensor not (yet) supported: Entryway
[6/21/2019, 6:27:26 PM] [Security] { type: 6,
  serial: '0039fef8',
  name: 'Entryway',
  setting:
   { instantTrigger: false,
     away2: 1,
     away: 1,
     home2: 1,
     home: 1,
     off: 0 },
  status: {},
  flags:
   { swingerShutdown: false, lowBattery: false, offline: false } }
[6/21/2019, 6:27:57 PM] [Security] Getting current state...
[6/21/2019, 6:27:57 PM] [Security] Getting target state...
[6/21/2019, 6:27:57 PM] [Security] Current alarm state is: 3
[6/21/2019, 6:27:57 PM] [Security] Target alarm state is: 3
[6/21/2019, 6:28:14 PM] [Security] Getting current state...
[6/21/2019, 6:28:14 PM] [Security] Getting target state...
[6/21/2019, 6:28:15 PM] [Security] Current alarm state is: 3
[6/21/2019, 6:28:15 PM] [Security] Target alarm state is: 3
[6/21/2019, 6:28:40 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:28:55 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:29:03 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:29:06 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:29:17 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:29:25 PM] [Config] [admin] Accessory layout changes saved.
[6/21/2019, 6:29:41 PM] [Security] Getting current state...
[6/21/2019, 6:29:41 PM] [Security] Getting target state...
[6/21/2019, 6:29:42 PM] [Security] Current alarm state is: 3
[6/21/2019, 6:29:42 PM] [Security] Target alarm state is: 3
[6/21/2019, 6:31:58 PM] [Security] Getting current state...
[6/21/2019, 6:31:58 PM] [Security] Getting target state...
[6/21/2019, 6:31:59 PM] [Security] Current alarm state is: 3
[6/21/2019, 6:31:59 PM] [Security] Target alarm state is: 3
[6/21/2019, 6:35:06 PM] [Security] Received new event from alarm: CAMERA_MOTION
[6/21/2019, 6:35:29 PM] [Security] Getting current state...
[6/21/2019, 6:35:29 PM] [Security] Getting target state...
[6/21/2019, 6:35:30 PM] [Security] Current alarm state is: 3
[6/21/2019, 6:35:30 PM] [Security] Target alarm state is: 3
[6/21/2019, 6:35:33 PM] [Security] Start streaming video from Living Room
[6/21/2019, 6:35:33 PM] [Security] /usr/local/lib/node_modules/homebridge-simplisafe3/node_modules/@ffmpeg-installer/linux-arm/ffmpeg -re -headers Authorization: Bearer V8Zv8LJFq2JM6GH85ehSqYsxDwx8Optj8TcAdz7Bil8= -i https://52.0.178.189/v1/b18e55d19dce5ecf8c598962c00d9277/flv?x=1280 -map 0:0 -vcodec libx264 -tune zerolatency -preset superfast -pix_fmt yuv420p -r 25 -f rawvideo -vf scale=1280:720 -b:v 284k -bufsize 284k -maxrate 284k -payload_type 99 -ssrc 12922376 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params /0x23mJfgi6G02V4+UhkfFTzy5Blk2KYu3m+cATz srtp://10.0.1.79:57383?rtcpport=57383&localrtcpport=57383&pkt_size=1316 -map 0:1 -acodec libopus -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -payload_type 110 -ssrc 11647702 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params o+TfoWuGkRDZRGYzPrntO0c7s3VEFss72nWOSKie srtp://10.0.1.79:50069?rtcpport=50069&localrtcpport=50069&pkt_size=1316
[6/21/2019, 6:35:33 PM] [Security] Stopped streaming`

**Comment by hubartt** [comment] 2019-06-21 23:12
Other notes:

The camera shows "No Response" both while on the local network and while I'm out of the house.

I'm happy to share any other details if they would be helpful.

**Comment by nzapponi** [comment] 2019-06-24 06:16
Hi @hubartt , from the logs you provided, the glass break sensor isn't supported as SimpliSafe does not provide any status information for it unfortunately.

Regarding the No Response on your camera, it may be that the Raspberry Pi Zero W isn't capable enough to encode the video stream, but that's my pure guess unfortunately..

I'll leave the issue open in case anyone comes up with an idea on how to fix this.

Thanks!

**Comment by tasansal** [comment] 2019-07-10 01:52
I can confirm that the cameras DO work on cellular but not on the same WiFi network. The logs show ffmpeg working (shows frame rates etc) but the video can’t get past loading. Cameras privacy shutter also open/close fine, just blank video.

I am running on a Synology NAS (onzu-homebridge) using docker; quad core celeron, the video looks great when it works.

**Comment by nzapponi** [comment] 2019-07-17 12:17
@tasansal are you by any chance running Homebridge on Docker?

**Comment by tasansal** [comment] 2019-07-18 15:07
@nzapponi, yes. I am running on NAS using docker (onzu-homebridge pkg); quad core x86 intel cpu.

**Comment by nzapponi** [comment] 2019-07-18 15:42
@tasansal ok thanks, it seems to be an issue related with oznu/homebridge... I just migrated my Homebridge setup to a native one and all of a sudden the camera is visible on the local network as well.

I will look into it but it may not be something in my hands to fix. I will update the README doc to mention this limitation.

I will also release an update tomorrow to add additional camera options.
Thanks

**Comment by nzapponi** [comment] 2019-07-18 17:27
Documentation updated in b48732c21c89b8a7b9945d08494f118d6ba2cfba, closing.

**Closed by nzapponi** 2019-07-18 17:27 UTC
