### ISSUE TITLE
TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by kameshtagore** [nzapponi/homebridge-simplisafe3#64] opened 2020-01-30 05:21 UTC
Hello,
Thanks for providing this plugin. I have updated the plugin to 1.4.0 and started seeing this error message. This happens randomly in a day or two after restarting homebridge. I am running node version 12.3.1.

[1/27/2020, 2:47:11 AM] [Simplisafe] Real time events disconnected.
[1/27/2020, 2:47:11 AM] [Simplisafe] Listening to alarm events...
[1/27/2020, 2:47:11 AM] [Simplisafe] Received new event from alarm: DISCONNECT
[1/27/2020, 2:47:11 AM] [Simplisafe] Real time events disconnected.
[1/27/2020, 2:47:11 AM] [Simplisafe] Listening to alarm events...
[1/27/2020, 2:47:18 AM] TypeError: Cannot read property 'destroy' of null
    at EventedHTTPServerConnection._onClientSocketClose (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:326:22)
    at Socket.emit (events.js:200:13)
    at TCP.<anonymous> (net.js:586:12)
[1/27/2020, 2:47:25 AM] Got SIGTERM, shutting down Homebridge...

**Comment by nzapponi** [comment] 2020-01-30 12:26
Seems like a socket.io issue, potentially due to internet disconnecting?..
Can you please let me know if it happens again?

**Comment by kameshtagore** [comment] 2020-02-03 07:13
This happened again today. I have four instances of homebridge running, one for Nest, one for TP-Link, one for Vesync and one for simplisafe3. Only the SS3 instance is facing this issue.

[2/1/2020, 6:48:26 PM] TypeError: Cannot read property 'destroy' of null
    at EventedHTTPServerConnection._onClientSocketClose (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:326:22)
    at Socket.emit (events.js:200:13)
    at TCP.<anonymous> (net.js:586:12)

**Comment by nikonratm** [comment] 2020-02-03 08:34
This looks like a bug that was fixed in HAP-NodeJS, not sure why you’re the only person getting it. Homebridge is using an old version of HAP-NodeJSwhihc should hopefully be updated. https://github.com/KhaosT/HAP-NodeJS/blob/80de04372a9ac3a3bce884e9699a4c72b41b0d23/lib/util/eventedhttp.js#L326 but in newest version the function doesn’t call `destroy` if the socket is empty, eg doesn’t throw this error https://github.com/KhaosT/HAP-NodeJS/blob/52abfb360f8d65a7ec73ded685db5b8a58d0c2b7/src/lib/util/eventedhttp.ts#L494

**Comment by nikonratm** [comment] 2020-02-15 16:25
@JoshuaHolme from #80: The latest plugin update should have fixed this and added some extra logging to try and find the cause. Can you confirm you are running the latest one? Can you send more of the logs before the error? Please copy / paste text instead of screenshots.

**Comment by JoshuaHolme** [comment] 2020-02-15 16:39
@nikonratm What's the best way to find that?

**Comment by nikonratm** [comment] 2020-02-15 16:43
In the terminal type `npm list -g --depth=0`, for node just type `node -v`

**Comment by JoshuaHolme** [comment] 2020-02-15 16:48
This plugin is version `1.4.0` and node is version `12.7.0`

**Comment by nikonratm** [comment] 2020-02-15 17:41
Both of those are outdated, please update and let us know how you get on

**Comment by JoshuaHolme** [comment] 2020-02-15 18:22
What’s the best way to update this plugin without having to reconfigure everything?

**Comment by nzapponi** [comment] 2020-02-15 18:54
To update, Just run `npm install -g —unsafe-perm homebridge-simplisafe3` and then restart Homebridge. Thanks!

**Comment by nikonratm** [comment] 2020-02-15 20:19
And to update node see https://medium.com/stackfame/how-to-update-node-js-to-latest-version-linux-ubuntu-osx-windows-others-105749e90040 (or just google around)

You may also want to look at something like https://github.com/oznu/homebridge-config-ui-x or even https://hoobs.org/product/hoobs-to-download/ as those tools are a little more user-friendly if you’re less comfortable managing everything yourself

**Comment by JoshuaHolme** [comment] 2020-02-15 22:26
Have updated both. Will write back if it happens again.

**Comment by JoshuaHolme** [comment] 2020-03-05 19:02
Just wanted to update, haven’t seen that issue pop back up since updating those. Thank you for the help!

**Comment by nikonratm** [comment] 2020-03-05 19:06
Excellent! Please close this issue when you have a moment.

**Comment by JoshuaHolme** [comment] 2020-03-05 21:19
I didn’t open this issue though, should I still be the one to close it?

**Comment by nikonratm** [comment] 2020-03-05 21:20
Aha. Nope =)

**Closed** 2020-03-05 21:38 UTC
