### ISSUE TITLE
Updating bug

### ISSUE THREAD

**Issue by dcstroud** [nzapponi/homebridge-simplisafe3#50] opened 2019-12-14 12:57 UTC
I have noticed anytime I disarm from the SimpliSafe keypad, if I go to the home app, the tile is stuck on arming.  It will never update until I go in Home and select Off.

**Comment by nikonratm** [comment] 2019-12-14 15:57
Hmm, I can’t replicate this. Does it matter if you’re disarming from “Home” or “Away” or happens with both?

**Comment by nikonratm** [comment] 2019-12-14 15:59
Also, I’m assuming you’ve tried simple stuff like restarting Homebridge and restarting your home hub?

**Comment by nikonratm** [comment] 2020-01-05 18:07
If this issue is resolved please close. Thanks.

**Comment by dcstroud** [comment] 2020-01-05 20:56
Unfortunately, still dealing with it. Everything works correctly, just the updating of the status is what I am struggling with.

**Comment by nikonratm** [comment] 2020-01-05 22:18
Since it seems limited to you I have to wonder if its something about your setup. Have you tried simple steps I mentioned above, restarting things? Then you can try wiping Homebridge or even wiping your home (I know, some of those not practical). What type of hub are you using?

In general its an odd problem, if you arm the alarm, once its armed HomeKit should show "Home" or "Away", not "Arming..." any more. Therefore when you disable via keypad I would expect HomeKit to show one of those two things, not go back to "Arming...". Does it matter how (keypad / app) you arm it?

**Comment by dcstroud** [comment] 2020-01-06 00:20
Yeah, I went through the simple steps.  I tried it on a new instance of Homebridge as well. Seems like it is tied to HomeKit Automations. I have a good night routine that also arms the alarm, it will only show arming instead of armed. Could be a HomeKit issue.

**Comment by dcstroud** [comment] 2020-01-06 01:57
Only hubs in use are Phillips Hue, Homebridge (HOOBS 3.1.1) and AppleTv.

**Comment by nikonratm** [comment] 2020-01-06 03:23
Ok so scenario is scheduled automation sets a scene that includes alarm "Home" (or "Away"?) and then some time later in the morning you disarm with the keypad and then regardless of which iOS device you use it is "stuck" on "Arming..."?

If thats correct, I have a similar automation so I can test and see if I can reproduce. A couple more qs:
- Does the bug occur when you manually set the "Away" scene or only after it automatically runs at night?
- Do you have any other scene / automations that change the alarm state? In other words, is it possible theres another automation or scene that could be conflicting? (Probably not, just asking).

**Comment by nikonratm** [comment] 2020-01-06 03:27
Sorry I meant "Good night" scene. And one more q: after the "Good night" scene automatically gets set (or even when its manually set) does the alarm state appear correct in the app? In other words before you disarm does it correctly show "Home" (and not "Arming...")?

**Comment by nikonratm** [comment] 2020-01-07 15:06
I am unable to reproduce this. The only other thing that might help would be if you can provide Homebridge logs around the relevant times eg when the alarm auto-arms, when you unlock via the keypad as well as when you open your iOS device to “un-stick” it from the “Arming...” state.

**Comment by nzapponi** [comment] 2020-01-07 15:38
@nikonratm and @dcstroud - I believe this could be due to the usual rate limiting that SimpliSafe does when you ping their APIs too much. I've had the same issue yesterday.

Can you try to turn off Homebridge for a couple of hours and try again?

**Comment by nzapponi** [comment] 2020-01-24 06:58
See #57 , same issue.

**Comment by nzapponi** [comment] 2020-01-30 12:25
Should be fixed by #60

**Comment by nzapponi** [comment] 2020-01-31 15:21
Should be fixed in release v1.4.3 which should go out in the next few days

**Comment by nikonratm** [comment] 2020-01-31 19:16
And / or may be addressed by #67

**Comment by nikonratm** [comment] 2020-04-14 01:48
@nzapponi I think we can close this now, been ages (or give me admin priv =)

**Closed** 2020-04-15 17:14 UTC
