### ISSUE TITLE
Motion sensor error

### ISSUE THREAD

**Issue by bdjessup** [nzapponi/homebridge-simplisafe3#75] opened 2020-02-06 22:24 UTC
After adding motion sensors, the homebridge crashes with the following error:

`[Homebridge] [2/6/2020, 2:12:10 PM] TypeError: Cannot read property 'sensorSerial' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/accessories/motionSensor.js:92:28
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/simplisafe.js:823:9)
    at Socket.Emitter.emit (/home/hoobs/.hoobs/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/home/hoobs/.hoobs/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onclose (/home/hoobs/.hoobs/node_modules/socket.io-client/lib/socket.js:214:8)
    at Manager.<anonymous> (/home/hoobs/.hoobs/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/hoobs/.hoobs/node_modules/component-emitter/index.js:133:20)
    at Manager.onclose (/home/hoobs/.hoobs/node_modules/socket.io-client/lib/manager.js:502:8)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/home/hoobs/.hoobs/node_modules/component-emitter/index.js:133:20)`

**Comment by nikonratm** [comment] 2020-02-07 04:20
Hmm thanks for letting us know, sounds like it’s solved correct? If so, please close this when you have a sec. We’ll look out for others having anything similar.

**Comment by bdjessup** [comment] 2020-02-07 17:02
After resuming the homebridge service it will eventually crash again after a few hours (same sensorSerial error).

**Comment by nikonratm** [comment] 2020-02-07 17:20
I will submit a PR to fix this, we have a similar fix in place in the camera listener (https://github.com/nikonratm/homebridge-simplisafe3/blob/517c9cc0a2789188c09f57f0f12de7267c15117e/src/accessories/simplicam.js#L120) e.g. sometimes `data` is null.

**Closed** 2020-02-10 07:45 UTC

**Comment by nzapponi** [comment] 2020-02-10 07:51
@bdjessup the issue should be fixed via the workaround that @nikonratm provided - thanks for that.

However I'd like to understand the root cause of it. I added some logging - would you mind check every now and then if you get a "Unknown SimpliSafe event" in the Homebridge log, and provide the data of that event when that is the case?

Thanks!
